CREATE TABLE books
(
    pk              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id              UUID                                    NOT NULL,
    title           VARCHAR(255)                            NOT NULL,
    author          VARCHAR(255),
    isbn            VARCHAR(255),
    release_date    date,
    description     VARCHAR(2000),
    language        VARCHAR(255),
    pages           INTEGER,
    publisher       VARCHAR(255),
    genre           VARCHAR(255),
    cover_image_url VARCHAR(255),
    created_at      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    library_id      BIGINT                                  NOT NULL,
    CONSTRAINT pk_books PRIMARY KEY (pk)
);

CREATE TABLE comments
(
    pk         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id         UUID                                    NOT NULL,
    text       VARCHAR(1000)                           NOT NULL,
    rating     INTEGER,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    user_id    BIGINT                                  NOT NULL,
    book_id    BIGINT                                  NOT NULL,
    CONSTRAINT pk_comments PRIMARY KEY (pk)
);

CREATE TABLE libraries
(
    pk             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id             UUID                                    NOT NULL,
    title          VARCHAR(255)                            NOT NULL,
    description    VARCHAR(255),
    color          VARCHAR(255),
    privacy_status VARCHAR(255),
    is_editable    BOOLEAN,
    created_at     TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at     TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    user_id        BIGINT                                  NOT NULL,
    CONSTRAINT pk_libraries PRIMARY KEY (pk)
);

CREATE TABLE users
(
    pk            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id            UUID                                    NOT NULL,
    name          VARCHAR(255)                            NOT NULL,
    surname       VARCHAR(255)                            NOT NULL,
    username      VARCHAR(255)                            NOT NULL,
    email         VARCHAR(255)                            NOT NULL,
    date_of_birth date                                    NOT NULL,
    role          VARCHAR(255),
    created_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (pk)
);

ALTER TABLE books
    ADD CONSTRAINT uc_books_id UNIQUE (id);

ALTER TABLE books
    ADD CONSTRAINT uc_books_isbn UNIQUE (isbn);

ALTER TABLE comments
    ADD CONSTRAINT uc_comments_id UNIQUE (id);

ALTER TABLE libraries
    ADD CONSTRAINT uc_libraries_id UNIQUE (id);

ALTER TABLE users
    ADD CONSTRAINT uc_users_id UNIQUE (id);

ALTER TABLE users
    ADD CONSTRAINT uc_users_username UNIQUE (username);

ALTER TABLE books
    ADD CONSTRAINT FK_BOOKS_ON_LIBRARY FOREIGN KEY (library_id) REFERENCES libraries (pk);

ALTER TABLE comments
    ADD CONSTRAINT FK_COMMENTS_ON_BOOK FOREIGN KEY (book_id) REFERENCES books (pk);

ALTER TABLE comments
    ADD CONSTRAINT FK_COMMENTS_ON_USER FOREIGN KEY (user_id) REFERENCES users (pk);

ALTER TABLE libraries
    ADD CONSTRAINT FK_LIBRARIES_ON_USER FOREIGN KEY (user_id) REFERENCES users (pk);